/*
AdGuard Home

AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API. 

API version: 0.107
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FilterSetUrlData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FilterSetUrlData{}

// FilterSetUrlData Filter update data
type FilterSetUrlData struct {
	Enabled bool `json:"enabled"`
	Name string `json:"name"`
	Url string `json:"url"`
}

type _FilterSetUrlData FilterSetUrlData

// NewFilterSetUrlData instantiates a new FilterSetUrlData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilterSetUrlData(enabled bool, name string, url string) *FilterSetUrlData {
	this := FilterSetUrlData{}
	this.Enabled = enabled
	this.Name = name
	this.Url = url
	return &this
}

// NewFilterSetUrlDataWithDefaults instantiates a new FilterSetUrlData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilterSetUrlDataWithDefaults() *FilterSetUrlData {
	this := FilterSetUrlData{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *FilterSetUrlData) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *FilterSetUrlData) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *FilterSetUrlData) SetEnabled(v bool) {
	o.Enabled = v
}

// GetName returns the Name field value
func (o *FilterSetUrlData) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *FilterSetUrlData) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *FilterSetUrlData) SetName(v string) {
	o.Name = v
}

// GetUrl returns the Url field value
func (o *FilterSetUrlData) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *FilterSetUrlData) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *FilterSetUrlData) SetUrl(v string) {
	o.Url = v
}

func (o FilterSetUrlData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FilterSetUrlData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	toSerialize["name"] = o.Name
	toSerialize["url"] = o.Url
	return toSerialize, nil
}

func (o *FilterSetUrlData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabled",
		"name",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFilterSetUrlData := _FilterSetUrlData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFilterSetUrlData)

	if err != nil {
		return err
	}

	*o = FilterSetUrlData(varFilterSetUrlData)

	return err
}

type NullableFilterSetUrlData struct {
	value *FilterSetUrlData
	isSet bool
}

func (v NullableFilterSetUrlData) Get() *FilterSetUrlData {
	return v.value
}

func (v *NullableFilterSetUrlData) Set(val *FilterSetUrlData) {
	v.value = val
	v.isSet = true
}

func (v NullableFilterSetUrlData) IsSet() bool {
	return v.isSet
}

func (v *NullableFilterSetUrlData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilterSetUrlData(val *FilterSetUrlData) *NullableFilterSetUrlData {
	return &NullableFilterSetUrlData{value: val, isSet: true}
}

func (v NullableFilterSetUrlData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilterSetUrlData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


