/*
AdGuard Home

AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API. 

API version: 0.107
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CheckConfigRequestInfo type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckConfigRequestInfo{}

// CheckConfigRequestInfo struct for CheckConfigRequestInfo
type CheckConfigRequestInfo struct {
	Ip *string `json:"ip,omitempty"`
	Port *int32 `json:"port,omitempty"`
	Autofix *bool `json:"autofix,omitempty"`
}

// NewCheckConfigRequestInfo instantiates a new CheckConfigRequestInfo object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckConfigRequestInfo() *CheckConfigRequestInfo {
	this := CheckConfigRequestInfo{}
	return &this
}

// NewCheckConfigRequestInfoWithDefaults instantiates a new CheckConfigRequestInfo object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckConfigRequestInfoWithDefaults() *CheckConfigRequestInfo {
	this := CheckConfigRequestInfo{}
	return &this
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *CheckConfigRequestInfo) GetIp() string {
	if o == nil || IsNil(o.Ip) {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckConfigRequestInfo) GetIpOk() (*string, bool) {
	if o == nil || IsNil(o.Ip) {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *CheckConfigRequestInfo) HasIp() bool {
	if o != nil && !IsNil(o.Ip) {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *CheckConfigRequestInfo) SetIp(v string) {
	o.Ip = &v
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *CheckConfigRequestInfo) GetPort() int32 {
	if o == nil || IsNil(o.Port) {
		var ret int32
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckConfigRequestInfo) GetPortOk() (*int32, bool) {
	if o == nil || IsNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *CheckConfigRequestInfo) HasPort() bool {
	if o != nil && !IsNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given int32 and assigns it to the Port field.
func (o *CheckConfigRequestInfo) SetPort(v int32) {
	o.Port = &v
}

// GetAutofix returns the Autofix field value if set, zero value otherwise.
func (o *CheckConfigRequestInfo) GetAutofix() bool {
	if o == nil || IsNil(o.Autofix) {
		var ret bool
		return ret
	}
	return *o.Autofix
}

// GetAutofixOk returns a tuple with the Autofix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CheckConfigRequestInfo) GetAutofixOk() (*bool, bool) {
	if o == nil || IsNil(o.Autofix) {
		return nil, false
	}
	return o.Autofix, true
}

// HasAutofix returns a boolean if a field has been set.
func (o *CheckConfigRequestInfo) HasAutofix() bool {
	if o != nil && !IsNil(o.Autofix) {
		return true
	}

	return false
}

// SetAutofix gets a reference to the given bool and assigns it to the Autofix field.
func (o *CheckConfigRequestInfo) SetAutofix(v bool) {
	o.Autofix = &v
}

func (o CheckConfigRequestInfo) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckConfigRequestInfo) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Ip) {
		toSerialize["ip"] = o.Ip
	}
	if !IsNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	if !IsNil(o.Autofix) {
		toSerialize["autofix"] = o.Autofix
	}
	return toSerialize, nil
}

type NullableCheckConfigRequestInfo struct {
	value *CheckConfigRequestInfo
	isSet bool
}

func (v NullableCheckConfigRequestInfo) Get() *CheckConfigRequestInfo {
	return v.value
}

func (v *NullableCheckConfigRequestInfo) Set(val *CheckConfigRequestInfo) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckConfigRequestInfo) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckConfigRequestInfo) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckConfigRequestInfo(val *CheckConfigRequestInfo) *NullableCheckConfigRequestInfo {
	return &NullableCheckConfigRequestInfo{value: val, isSet: true}
}

func (v NullableCheckConfigRequestInfo) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckConfigRequestInfo) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


