/*
AdGuard Home

AdGuard Home REST-ish API.  Our admin web interface is built on top of this REST-ish API. 

API version: 0.107
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ClientFindSubEntry type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ClientFindSubEntry{}

// ClientFindSubEntry Client information.
type ClientFindSubEntry struct {
	// Name
	Name *string `json:"name,omitempty"`
	// IP, CIDR, MAC, or ClientID.
	Ids []string `json:"ids,omitempty"`
	UseGlobalSettings *bool `json:"use_global_settings,omitempty"`
	FilteringEnabled *bool `json:"filtering_enabled,omitempty"`
	ParentalEnabled *bool `json:"parental_enabled,omitempty"`
	SafebrowsingEnabled *bool `json:"safebrowsing_enabled,omitempty"`
	// Deprecated
	SafesearchEnabled *bool `json:"safesearch_enabled,omitempty"`
	SafeSearch *SafeSearchConfig `json:"safe_search,omitempty"`
	UseGlobalBlockedServices *bool `json:"use_global_blocked_services,omitempty"`
	BlockedServices []string `json:"blocked_services,omitempty"`
	Upstreams []string `json:"upstreams,omitempty"`
	WhoisInfo *map[string]string `json:"whois_info,omitempty"`
	// Whether the client's IP is blocked or not. 
	Disallowed *bool `json:"disallowed,omitempty"`
	// The rule due to which the client is disallowed.  If disallowed is set to true, and this string is empty, then the client IP is disallowed by the \"allowed IP list\", that is it is not included in the allowed list. 
	DisallowedRule *string `json:"disallowed_rule,omitempty"`
	IgnoreQuerylog *bool `json:"ignore_querylog,omitempty"`
	IgnoreStatistics *bool `json:"ignore_statistics,omitempty"`
}

// NewClientFindSubEntry instantiates a new ClientFindSubEntry object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClientFindSubEntry() *ClientFindSubEntry {
	this := ClientFindSubEntry{}
	return &this
}

// NewClientFindSubEntryWithDefaults instantiates a new ClientFindSubEntry object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClientFindSubEntryWithDefaults() *ClientFindSubEntry {
	this := ClientFindSubEntry{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ClientFindSubEntry) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientFindSubEntry) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ClientFindSubEntry) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ClientFindSubEntry) SetName(v string) {
	o.Name = &v
}

// GetIds returns the Ids field value if set, zero value otherwise.
func (o *ClientFindSubEntry) GetIds() []string {
	if o == nil || IsNil(o.Ids) {
		var ret []string
		return ret
	}
	return o.Ids
}

// GetIdsOk returns a tuple with the Ids field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientFindSubEntry) GetIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.Ids) {
		return nil, false
	}
	return o.Ids, true
}

// HasIds returns a boolean if a field has been set.
func (o *ClientFindSubEntry) HasIds() bool {
	if o != nil && !IsNil(o.Ids) {
		return true
	}

	return false
}

// SetIds gets a reference to the given []string and assigns it to the Ids field.
func (o *ClientFindSubEntry) SetIds(v []string) {
	o.Ids = v
}

// GetUseGlobalSettings returns the UseGlobalSettings field value if set, zero value otherwise.
func (o *ClientFindSubEntry) GetUseGlobalSettings() bool {
	if o == nil || IsNil(o.UseGlobalSettings) {
		var ret bool
		return ret
	}
	return *o.UseGlobalSettings
}

// GetUseGlobalSettingsOk returns a tuple with the UseGlobalSettings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientFindSubEntry) GetUseGlobalSettingsOk() (*bool, bool) {
	if o == nil || IsNil(o.UseGlobalSettings) {
		return nil, false
	}
	return o.UseGlobalSettings, true
}

// HasUseGlobalSettings returns a boolean if a field has been set.
func (o *ClientFindSubEntry) HasUseGlobalSettings() bool {
	if o != nil && !IsNil(o.UseGlobalSettings) {
		return true
	}

	return false
}

// SetUseGlobalSettings gets a reference to the given bool and assigns it to the UseGlobalSettings field.
func (o *ClientFindSubEntry) SetUseGlobalSettings(v bool) {
	o.UseGlobalSettings = &v
}

// GetFilteringEnabled returns the FilteringEnabled field value if set, zero value otherwise.
func (o *ClientFindSubEntry) GetFilteringEnabled() bool {
	if o == nil || IsNil(o.FilteringEnabled) {
		var ret bool
		return ret
	}
	return *o.FilteringEnabled
}

// GetFilteringEnabledOk returns a tuple with the FilteringEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientFindSubEntry) GetFilteringEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.FilteringEnabled) {
		return nil, false
	}
	return o.FilteringEnabled, true
}

// HasFilteringEnabled returns a boolean if a field has been set.
func (o *ClientFindSubEntry) HasFilteringEnabled() bool {
	if o != nil && !IsNil(o.FilteringEnabled) {
		return true
	}

	return false
}

// SetFilteringEnabled gets a reference to the given bool and assigns it to the FilteringEnabled field.
func (o *ClientFindSubEntry) SetFilteringEnabled(v bool) {
	o.FilteringEnabled = &v
}

// GetParentalEnabled returns the ParentalEnabled field value if set, zero value otherwise.
func (o *ClientFindSubEntry) GetParentalEnabled() bool {
	if o == nil || IsNil(o.ParentalEnabled) {
		var ret bool
		return ret
	}
	return *o.ParentalEnabled
}

// GetParentalEnabledOk returns a tuple with the ParentalEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientFindSubEntry) GetParentalEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.ParentalEnabled) {
		return nil, false
	}
	return o.ParentalEnabled, true
}

// HasParentalEnabled returns a boolean if a field has been set.
func (o *ClientFindSubEntry) HasParentalEnabled() bool {
	if o != nil && !IsNil(o.ParentalEnabled) {
		return true
	}

	return false
}

// SetParentalEnabled gets a reference to the given bool and assigns it to the ParentalEnabled field.
func (o *ClientFindSubEntry) SetParentalEnabled(v bool) {
	o.ParentalEnabled = &v
}

// GetSafebrowsingEnabled returns the SafebrowsingEnabled field value if set, zero value otherwise.
func (o *ClientFindSubEntry) GetSafebrowsingEnabled() bool {
	if o == nil || IsNil(o.SafebrowsingEnabled) {
		var ret bool
		return ret
	}
	return *o.SafebrowsingEnabled
}

// GetSafebrowsingEnabledOk returns a tuple with the SafebrowsingEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientFindSubEntry) GetSafebrowsingEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.SafebrowsingEnabled) {
		return nil, false
	}
	return o.SafebrowsingEnabled, true
}

// HasSafebrowsingEnabled returns a boolean if a field has been set.
func (o *ClientFindSubEntry) HasSafebrowsingEnabled() bool {
	if o != nil && !IsNil(o.SafebrowsingEnabled) {
		return true
	}

	return false
}

// SetSafebrowsingEnabled gets a reference to the given bool and assigns it to the SafebrowsingEnabled field.
func (o *ClientFindSubEntry) SetSafebrowsingEnabled(v bool) {
	o.SafebrowsingEnabled = &v
}

// GetSafesearchEnabled returns the SafesearchEnabled field value if set, zero value otherwise.
// Deprecated
func (o *ClientFindSubEntry) GetSafesearchEnabled() bool {
	if o == nil || IsNil(o.SafesearchEnabled) {
		var ret bool
		return ret
	}
	return *o.SafesearchEnabled
}

// GetSafesearchEnabledOk returns a tuple with the SafesearchEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
// Deprecated
func (o *ClientFindSubEntry) GetSafesearchEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.SafesearchEnabled) {
		return nil, false
	}
	return o.SafesearchEnabled, true
}

// HasSafesearchEnabled returns a boolean if a field has been set.
func (o *ClientFindSubEntry) HasSafesearchEnabled() bool {
	if o != nil && !IsNil(o.SafesearchEnabled) {
		return true
	}

	return false
}

// SetSafesearchEnabled gets a reference to the given bool and assigns it to the SafesearchEnabled field.
// Deprecated
func (o *ClientFindSubEntry) SetSafesearchEnabled(v bool) {
	o.SafesearchEnabled = &v
}

// GetSafeSearch returns the SafeSearch field value if set, zero value otherwise.
func (o *ClientFindSubEntry) GetSafeSearch() SafeSearchConfig {
	if o == nil || IsNil(o.SafeSearch) {
		var ret SafeSearchConfig
		return ret
	}
	return *o.SafeSearch
}

// GetSafeSearchOk returns a tuple with the SafeSearch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientFindSubEntry) GetSafeSearchOk() (*SafeSearchConfig, bool) {
	if o == nil || IsNil(o.SafeSearch) {
		return nil, false
	}
	return o.SafeSearch, true
}

// HasSafeSearch returns a boolean if a field has been set.
func (o *ClientFindSubEntry) HasSafeSearch() bool {
	if o != nil && !IsNil(o.SafeSearch) {
		return true
	}

	return false
}

// SetSafeSearch gets a reference to the given SafeSearchConfig and assigns it to the SafeSearch field.
func (o *ClientFindSubEntry) SetSafeSearch(v SafeSearchConfig) {
	o.SafeSearch = &v
}

// GetUseGlobalBlockedServices returns the UseGlobalBlockedServices field value if set, zero value otherwise.
func (o *ClientFindSubEntry) GetUseGlobalBlockedServices() bool {
	if o == nil || IsNil(o.UseGlobalBlockedServices) {
		var ret bool
		return ret
	}
	return *o.UseGlobalBlockedServices
}

// GetUseGlobalBlockedServicesOk returns a tuple with the UseGlobalBlockedServices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientFindSubEntry) GetUseGlobalBlockedServicesOk() (*bool, bool) {
	if o == nil || IsNil(o.UseGlobalBlockedServices) {
		return nil, false
	}
	return o.UseGlobalBlockedServices, true
}

// HasUseGlobalBlockedServices returns a boolean if a field has been set.
func (o *ClientFindSubEntry) HasUseGlobalBlockedServices() bool {
	if o != nil && !IsNil(o.UseGlobalBlockedServices) {
		return true
	}

	return false
}

// SetUseGlobalBlockedServices gets a reference to the given bool and assigns it to the UseGlobalBlockedServices field.
func (o *ClientFindSubEntry) SetUseGlobalBlockedServices(v bool) {
	o.UseGlobalBlockedServices = &v
}

// GetBlockedServices returns the BlockedServices field value if set, zero value otherwise.
func (o *ClientFindSubEntry) GetBlockedServices() []string {
	if o == nil || IsNil(o.BlockedServices) {
		var ret []string
		return ret
	}
	return o.BlockedServices
}

// GetBlockedServicesOk returns a tuple with the BlockedServices field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientFindSubEntry) GetBlockedServicesOk() ([]string, bool) {
	if o == nil || IsNil(o.BlockedServices) {
		return nil, false
	}
	return o.BlockedServices, true
}

// HasBlockedServices returns a boolean if a field has been set.
func (o *ClientFindSubEntry) HasBlockedServices() bool {
	if o != nil && !IsNil(o.BlockedServices) {
		return true
	}

	return false
}

// SetBlockedServices gets a reference to the given []string and assigns it to the BlockedServices field.
func (o *ClientFindSubEntry) SetBlockedServices(v []string) {
	o.BlockedServices = v
}

// GetUpstreams returns the Upstreams field value if set, zero value otherwise.
func (o *ClientFindSubEntry) GetUpstreams() []string {
	if o == nil || IsNil(o.Upstreams) {
		var ret []string
		return ret
	}
	return o.Upstreams
}

// GetUpstreamsOk returns a tuple with the Upstreams field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientFindSubEntry) GetUpstreamsOk() ([]string, bool) {
	if o == nil || IsNil(o.Upstreams) {
		return nil, false
	}
	return o.Upstreams, true
}

// HasUpstreams returns a boolean if a field has been set.
func (o *ClientFindSubEntry) HasUpstreams() bool {
	if o != nil && !IsNil(o.Upstreams) {
		return true
	}

	return false
}

// SetUpstreams gets a reference to the given []string and assigns it to the Upstreams field.
func (o *ClientFindSubEntry) SetUpstreams(v []string) {
	o.Upstreams = v
}

// GetWhoisInfo returns the WhoisInfo field value if set, zero value otherwise.
func (o *ClientFindSubEntry) GetWhoisInfo() map[string]string {
	if o == nil || IsNil(o.WhoisInfo) {
		var ret map[string]string
		return ret
	}
	return *o.WhoisInfo
}

// GetWhoisInfoOk returns a tuple with the WhoisInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientFindSubEntry) GetWhoisInfoOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.WhoisInfo) {
		return nil, false
	}
	return o.WhoisInfo, true
}

// HasWhoisInfo returns a boolean if a field has been set.
func (o *ClientFindSubEntry) HasWhoisInfo() bool {
	if o != nil && !IsNil(o.WhoisInfo) {
		return true
	}

	return false
}

// SetWhoisInfo gets a reference to the given map[string]string and assigns it to the WhoisInfo field.
func (o *ClientFindSubEntry) SetWhoisInfo(v map[string]string) {
	o.WhoisInfo = &v
}

// GetDisallowed returns the Disallowed field value if set, zero value otherwise.
func (o *ClientFindSubEntry) GetDisallowed() bool {
	if o == nil || IsNil(o.Disallowed) {
		var ret bool
		return ret
	}
	return *o.Disallowed
}

// GetDisallowedOk returns a tuple with the Disallowed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientFindSubEntry) GetDisallowedOk() (*bool, bool) {
	if o == nil || IsNil(o.Disallowed) {
		return nil, false
	}
	return o.Disallowed, true
}

// HasDisallowed returns a boolean if a field has been set.
func (o *ClientFindSubEntry) HasDisallowed() bool {
	if o != nil && !IsNil(o.Disallowed) {
		return true
	}

	return false
}

// SetDisallowed gets a reference to the given bool and assigns it to the Disallowed field.
func (o *ClientFindSubEntry) SetDisallowed(v bool) {
	o.Disallowed = &v
}

// GetDisallowedRule returns the DisallowedRule field value if set, zero value otherwise.
func (o *ClientFindSubEntry) GetDisallowedRule() string {
	if o == nil || IsNil(o.DisallowedRule) {
		var ret string
		return ret
	}
	return *o.DisallowedRule
}

// GetDisallowedRuleOk returns a tuple with the DisallowedRule field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientFindSubEntry) GetDisallowedRuleOk() (*string, bool) {
	if o == nil || IsNil(o.DisallowedRule) {
		return nil, false
	}
	return o.DisallowedRule, true
}

// HasDisallowedRule returns a boolean if a field has been set.
func (o *ClientFindSubEntry) HasDisallowedRule() bool {
	if o != nil && !IsNil(o.DisallowedRule) {
		return true
	}

	return false
}

// SetDisallowedRule gets a reference to the given string and assigns it to the DisallowedRule field.
func (o *ClientFindSubEntry) SetDisallowedRule(v string) {
	o.DisallowedRule = &v
}

// GetIgnoreQuerylog returns the IgnoreQuerylog field value if set, zero value otherwise.
func (o *ClientFindSubEntry) GetIgnoreQuerylog() bool {
	if o == nil || IsNil(o.IgnoreQuerylog) {
		var ret bool
		return ret
	}
	return *o.IgnoreQuerylog
}

// GetIgnoreQuerylogOk returns a tuple with the IgnoreQuerylog field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientFindSubEntry) GetIgnoreQuerylogOk() (*bool, bool) {
	if o == nil || IsNil(o.IgnoreQuerylog) {
		return nil, false
	}
	return o.IgnoreQuerylog, true
}

// HasIgnoreQuerylog returns a boolean if a field has been set.
func (o *ClientFindSubEntry) HasIgnoreQuerylog() bool {
	if o != nil && !IsNil(o.IgnoreQuerylog) {
		return true
	}

	return false
}

// SetIgnoreQuerylog gets a reference to the given bool and assigns it to the IgnoreQuerylog field.
func (o *ClientFindSubEntry) SetIgnoreQuerylog(v bool) {
	o.IgnoreQuerylog = &v
}

// GetIgnoreStatistics returns the IgnoreStatistics field value if set, zero value otherwise.
func (o *ClientFindSubEntry) GetIgnoreStatistics() bool {
	if o == nil || IsNil(o.IgnoreStatistics) {
		var ret bool
		return ret
	}
	return *o.IgnoreStatistics
}

// GetIgnoreStatisticsOk returns a tuple with the IgnoreStatistics field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ClientFindSubEntry) GetIgnoreStatisticsOk() (*bool, bool) {
	if o == nil || IsNil(o.IgnoreStatistics) {
		return nil, false
	}
	return o.IgnoreStatistics, true
}

// HasIgnoreStatistics returns a boolean if a field has been set.
func (o *ClientFindSubEntry) HasIgnoreStatistics() bool {
	if o != nil && !IsNil(o.IgnoreStatistics) {
		return true
	}

	return false
}

// SetIgnoreStatistics gets a reference to the given bool and assigns it to the IgnoreStatistics field.
func (o *ClientFindSubEntry) SetIgnoreStatistics(v bool) {
	o.IgnoreStatistics = &v
}

func (o ClientFindSubEntry) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ClientFindSubEntry) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Ids) {
		toSerialize["ids"] = o.Ids
	}
	if !IsNil(o.UseGlobalSettings) {
		toSerialize["use_global_settings"] = o.UseGlobalSettings
	}
	if !IsNil(o.FilteringEnabled) {
		toSerialize["filtering_enabled"] = o.FilteringEnabled
	}
	if !IsNil(o.ParentalEnabled) {
		toSerialize["parental_enabled"] = o.ParentalEnabled
	}
	if !IsNil(o.SafebrowsingEnabled) {
		toSerialize["safebrowsing_enabled"] = o.SafebrowsingEnabled
	}
	if !IsNil(o.SafesearchEnabled) {
		toSerialize["safesearch_enabled"] = o.SafesearchEnabled
	}
	if !IsNil(o.SafeSearch) {
		toSerialize["safe_search"] = o.SafeSearch
	}
	if !IsNil(o.UseGlobalBlockedServices) {
		toSerialize["use_global_blocked_services"] = o.UseGlobalBlockedServices
	}
	if !IsNil(o.BlockedServices) {
		toSerialize["blocked_services"] = o.BlockedServices
	}
	if !IsNil(o.Upstreams) {
		toSerialize["upstreams"] = o.Upstreams
	}
	if !IsNil(o.WhoisInfo) {
		toSerialize["whois_info"] = o.WhoisInfo
	}
	if !IsNil(o.Disallowed) {
		toSerialize["disallowed"] = o.Disallowed
	}
	if !IsNil(o.DisallowedRule) {
		toSerialize["disallowed_rule"] = o.DisallowedRule
	}
	if !IsNil(o.IgnoreQuerylog) {
		toSerialize["ignore_querylog"] = o.IgnoreQuerylog
	}
	if !IsNil(o.IgnoreStatistics) {
		toSerialize["ignore_statistics"] = o.IgnoreStatistics
	}
	return toSerialize, nil
}

type NullableClientFindSubEntry struct {
	value *ClientFindSubEntry
	isSet bool
}

func (v NullableClientFindSubEntry) Get() *ClientFindSubEntry {
	return v.value
}

func (v *NullableClientFindSubEntry) Set(val *ClientFindSubEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableClientFindSubEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableClientFindSubEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClientFindSubEntry(val *ClientFindSubEntry) *NullableClientFindSubEntry {
	return &NullableClientFindSubEntry{value: val, isSet: true}
}

func (v NullableClientFindSubEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClientFindSubEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


